# Autogenerated wrapper script for EinsteinToolkit_jll for x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich-march+avx2
export cactus_sim

using CompilerSupportLibraries_jll
using FFTW_jll
using GSL_jll
using HDF5_jll
using Hwloc_jll
using JpegTurbo_jll
using OpenBLAS32_jll
using OpenSSL_jll
using Zlib_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("EinsteinToolkit")
JLLWrappers.@declare_executable_product(cactus_sim)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, FFTW_jll, GSL_jll, HDF5_jll, Hwloc_jll, JpegTurbo_jll, OpenBLAS32_jll, OpenSSL_jll, Zlib_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        cactus_sim,
        "bin/cactus_sim",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
